server:
  port: 5000
  servlet:
    context-path: /

spring:
  application:
    name: qrcode-demo
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

wechat:
  token: abcd123456

qrcode:
  default-url: https://www.sohu.com
  width: 300
  height: 300
  check-template-location: true  # 添加这个
  image-format: PNG